name: "Push Source Files to Applanga"
on:
 push:
   branches:
     - main
   paths:
     - react_json_sample/en/*.json
   
jobs:
  push-sources-for-translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: 'checkout'
      - uses: applanga/setup-applanga-cli@v1.0.1
        with:
          version: 1.0.48
      - name: Push Sources to Applanga
        env: 
         APPLANGA_ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
        run: applanga push --force
        working-directory: checkout
        
