name: "Pull Target Files from Applanga"
on:
  schedule:
   - cron:  '* 23 * * *'
  repository_dispatch:
    types: [applanga-pull]
jobs:
  pull-translation-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          path: 'checkout'
      - uses: applanga/setup-applanga-cli@v1.0.1
        with:
          version: 1.0.48
      - name: Pull translations from Applanga
        env: 
         APPLANGA_ACCESS_TOKEN: ${{ secrets.APPLANGA_ACCESS_TOKEN }}
        run: applanga pull
        working-directory: checkout
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          branch: newTranslations
          commit-message: Updated translations
          title: Updated translations 
          body: Pulled in new translations from Applanga portal
          path: 'checkout'
